# Variables used to generate this project with Cookiecutter,
# provide this file to the `--config-file` command-line option to reuse them
#
# Made with Galactipy (release v3.2.1), see available options at:
# https://gitlab.com/galactipy/galactipy/blob/master/README.md#input-variables
default_context:
  project_name: "{{ cookiecutter.project_name }}"
  repo_name: "{{ cookiecutter.repo_name }}"
  package_name: "{{ cookiecutter.package_name }}"
  project_description: "{{ cookiecutter.project_description }}"
  copyright: "{{ cookiecutter.copyright }}"
  maintainer: "{{ cookiecutter.maintainer }}"
  scm_platform: "{{ cookiecutter.scm_platform }}"
  scm_namespace: "{{ cookiecutter.scm_namespace }}"
  email: "{{ cookiecutter.email }}"
  licence: "{{ cookiecutter.licence }}"
  minimal_python_version: "{{ cookiecutter.minimal_python_version }}"
  line_length: {{ cookiecutter.line_length }}
  docstring_style: "{{ cookiecutter.docstring_style }}"
  docstring_length: {{ cookiecutter.docstring_length }}
  version_schema: "{{ cookiecutter.version_schema }}"
  commit_convention: "{{ cookiecutter.commit_convention }}"
  use_bdd: {{ cookiecutter.use_bdd }}
  coverage_service: "{{ cookiecutter.coverage_service }}"
  create_docker: {{ cookiecutter.create_docker }}
  create_docs: {{ cookiecutter.create_docs }}
  app_type: "{{ cookiecutter.app_type }}"
