[project]
site_name = "{{ cookiecutter.project_name }} Documentation"
copyright = "Copyright &copy; {% now 'local', '%Y' %} {{ cookiecutter.copyright }}"

nav = [
  { "Home" = "index.md" },
  { "Getting Started" = [
    "getting_started/index.md",
    "getting_started/install.md",
    "getting_started/overview.md",
    { "1-Minute Tutorials" = [
      "getting_started/intro_tutorials/index.md",
    ] },
    { "Comparison with other Tools" = [
      "getting_started/comparison/index.md",
    ] },
    "getting_started/tutorials.md",
  ] },
  { "User Guide" = [
    "user_guide/index.md",
    "user_guide/10min.md",
    "user_guide/basics.md",
    "user_guide/advanced.md",
    "user_guide/gotchas.md",
    "user_guide/faq.md",
    "user_guide/options.md",
  ] },
  { "API Reference" = [
    "reference/index.md",
    { "Configuration" = [
      "reference/config/index.md",
      { "AppManager" = [
        "reference/config/app_manager/index.md",
        "reference/config/app_manager/init.md",
        "reference/config/app_manager/default.md",
        "reference/config/app_manager/custom.md",
      ]},
      { "ConfigurationDomain" = [
        "reference/config/configuration_domain/index.md",
        "reference/config/configuration_domain/from_flag.md",
      ]},
      "reference/config/resolve_app_manager.md",
    ]},
    { "Utilities" = [
      "reference/utilities/index.md",
      "reference/utilities/setup_app_logging.md",
  ] },
  ] },
  { "Development" = "development/index.md" },
  { "What's New" = "whatsnew/index.md" },
]


[project.theme]
features = [
  "navigation.indexes",
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.path",
  "navigation.expand",
  "navigation.top",
  "navigation.footer",
  "search.highlight",
  "toc.follow",
  "content.code.copy",
]


[project.theme.font]
code = "Cascadia Code"


[project.theme.palette]
scheme = "slate"
primary = "orange"
accent = "teal"


[project.plugins.mkdocstrings.handlers.python]
paths = ["{{ cookiecutter.package_name }}"]


[project.plugins.mkdocstrings.handlers.python.options]
{%- if cookiecutter.docstring_style != 'other' %}
docstring_style = "{{ cookiecutter.docstring_style }}"
{%- else %}
# UPDATEME by setting the value for `docstring_style`, see documentation at:
# https://mkdocstrings.github.io/python/usage/
{%- endif %}
show_source = false
show_bases = false
inherited_members = false

# Headings configuration
heading_level = 1
show_root_full_path = false
show_root_heading = true
show_symbol_type_heading = true
show_symbol_type_toc = true

# Docstring configuration
merge_init_into_class = true
docstring_options = { ignore_init_summary = true }
summary = true

# Signature configuration
line_length = {{ cookiecutter.docstring_length }}
separate_signature = true


[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.tables]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"


[[project.extra.social]]
icon = "fontawesome/brands/{{ cookiecutter.__scm_platform_lc }}"
link = "{{ cookiecutter.__scm_base_url }}"
name = "{{ cookiecutter.project_name }} development repository"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/{{ cookiecutter.repo_name }}/"
name = "PyPI package page"
{%- if cookiecutter.create_docker %}

[[project.extra.social]]
{%- if cookiecutter.__scm_platform_lc == 'gitlab' %}
icon = "fontawesome/solid/box-open"
link = "{{ cookiecutter.__docker_repo }}"
name = "{{ cookiecutter.project_name }} Container Registry"
{%- else %}
icon = "fontawesome/brands/docker"
link = "{{ cookiecutter.__docker_repo }}"
name = "{{ cookiecutter.project_name }} is on Docker Hub!"
{%- endif %}
{%- endif %}
