# Check GitHub Actions documentation at:
# https://github.com/marketplace/actions/pypi-publish
{%- raw %}
name: 👨‍🔬 TestPyPI Publishing

on:
  - pull_request
  - push:
      tags:
{%- endraw %}{% if cookiecutter.__schema_group == 'semver-like' %}
        - 'v?[0-9]+.[0-9]+.[0-9]+-*'
        - 'v?[0-9]+.[0-9]+.[0-9]+'
{%- elif cookiecutter.__schema_group == 'calver' %}
        - 'v?1?2?0?[0-9][0-9].[0-9]+.?0?[0-9]?[0-9]?-*'
        - 'v?1?2?0?[0-9][0-9].[0-9]+.?0?[0-9]?[0-9]?'
{%- elif cookiecutter.__schema_group == 'solover' %}
        - 'v?[0-9]+-*'
        - 'v?[0-9]+'
{%- endif %}{% raw %}

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: 🐍 Set up Python {% endraw %}{{ cookiecutter.minimal_python_version }}{% raw %}
        uses: actions/setup-python@v6
        with:
          python-version: "{% endraw %}{{ cookiecutter.minimal_python_version }}{% raw %}"

      - name: 💽 Install poetry
        uses: snok/install-poetry@v1

      - name: 📦 Build
        run: invoke build

      - name: 🗃️ Upload Builds
        uses: actions/upload-artifact@v7
        with:
          name: test-package-distribution
          path: dist/
          overwrite: true
          retention-days: 30

  deploy-test:
    name: Upload to TestPyPI
    runs-on: ubuntu-latest
    needs: build
    environment:
      # TODO Create the "development" environment in {% endraw %}{{ cookiecutter.__scm_link_url }}{% raw %}/settings/environments/new
      name: development
      url: https://test.pypi.org/p/{% endraw %}{{ cookiecutter.repo_name }}{% raw %}

    steps:
      - name: 🗃️ Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: test-package-distribution
          path: dist/

      - name: 📤 Deploy to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          # TODO Set the TESTPYPI_TOKEN variable for https://test.pypi.org in the development environment
          password: ${{ secrets.TESTPYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          attestations: false
{%- endraw %}
