# Check GitHub Actions documentation at:
# https://github.com/marketplace/actions/pypi-publish
{%- raw %}
name: 🔖 Publish to PyPI

on:
{%- endraw %}{% if cookiecutter.version_schema != 'trunkver' %}
  workflow_dispatch:
    inputs:
      publish:
        description: Allow publishing to PyPI in production
        required: true
        type: boolean
{%- else %}
  push:
    branches:
      - master
      - release-*
    paths:
      - {{ cookiecutter.package_name }}/**
      - tests/**
{% if cookiecutter.create_docker %}
      - docker/**
      - .dockerignore
{%- endif %}
      - .gitignore
{%- endif %}{% raw %}

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    if: ${{ inputs.publish }}

    steps:
      - uses: actions/checkout@v6

      - name: 🐍 Set up Python {% endraw %}{{ cookiecutter.minimal_python_version }}{% raw %}
        uses: actions/setup-python@v6
        with:
          python-version: "{% endraw %}{{ cookiecutter.minimal_python_version }}{% raw %}"

      - name: 💽 Install poetry
        uses: snok/install-poetry@v1
{%- endraw %}{% if cookiecutter.version_schema != 'trunkver' %}

      - name: 📦 Build
        run: invoke build
{%- else %}{% raw %}

      - name: Generate TrunkVer
        id: trunkver
        run: echo "pypi_version=$(date --utc '+%Y%m%d%H%M%S').0.0rc${{ github.run_id }}" >> $GITHUB_OUTPUT

        # FYI TrunkVer is not semantically compatible with PEP 440, this is a workaround
      - name: 📦 Build
        run: invoke build -l ${{ steps.trunkver.outputs.pypi_version }}
{%- endraw %}{% endif %}{% raw %}

      - name: 🗃️ Upload Builds
        uses: actions/upload-artifact@v7
        with:
          name: prod-package-distribution
          path: dist/
          overwrite: true
          retention-days: 30

  deploy-prod:
    name: Upload Release to PyPI
    runs-on: ubuntu-latest
    needs: build
{%- endraw %}{% if cookiecutter.version_schema != 'trunkver' %}{% raw %}
    if: ${{ inputs.publish && github.ref_type == 'tag' }}
{%- endraw %}{% endif %}{% raw %}
    environment:
      # TODO Create the "production" environment in {% endraw %}{{ cookiecutter.__scm_repo_latch }}{% raw %}/settings/environments/new
      name: production
      url: https://pypi.org/p/{% endraw %}{{ cookiecutter.repo_name }}{% raw %}
    permissions:
      # TODO Set up trusted publishing (https://docs.pypi.org/trusted-publishers/)
      id-token: write

    steps:
      - name: 🗃️ Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: prod-package-distribution
          path: dist/

      - name: 📤 Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@v1.13.0
{%- endraw %}
