# Check action documentation at:
# https://github.com/marketplace/actions/pypi-publish
{% raw %}
jobs:
  deploy-test:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/{% endraw %}{{ cookiecutter.repo_name }}{% raw %}
    steps:
    - name: Deploy to PyPI test environment
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # UPDATEME by setting the TESTPYPI_TOKEN variable for https://test.pypi.org in {{ cookiecutter.__scm_link_url }}/settings/secrets/actions/new
        password: ${{ secrets.TESTPYPI_TOKEN }}
        repository-url: https://test.pypi.org/legacy/

  deploy-prod:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/{% endraw %}{{ cookiecutter.repo_name }}{% raw %}
    permissions:
      # UPDATEME by setting up trusted publishing (https://docs.pypi.org/trusted-publishers/)
      id-token: write
    steps:
    - name: Deploy to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1{% endraw %}
